return {
  { import = "plugins.ui" },
  { import = "plugins.snacks" },
  { import = "plugins.fyler" },
  { import = "plugins.treesitter" },
  { import = "plugins.completion" },
  { import = "plugins.snippets" },
  { import = "plugins.surround" },
  { import = "plugins.git" },
  { import = "plugins.lsp" },
  { import = "plugins.dev" },
  { import = "plugins.formatting" },
  { import = "plugins.ai" },
  { import = "plugins.markview" },
}
